config:
  url: "https://www.dropbox.com/sh/4dflqzxa3ukcxgg/AAAVWn-u1ufOoY0l8bD3CqqQa?dl=1"
  item:
    material: RABBIT_HIDE
    custom-model-data: 11
  rocket:
    launch:
      time: 5 #in seconds
      speed: 2
    land:
      time: 8 #in seconds
      speed: 5
  MARS:
    landing-message: "&bYou have been landed to Mars"
    world: world
    location: 100,1300
    location2: 300,-1400
    specific-location: true
    cost: 100
    launching-radius: 8
    landing-radius: 6
    ocean-checker: true
  JUPITER:
    landing-message: "&bYou have been landed to Jupiter"
    world: world_nether
    location: 100,1300
    location2: 300,-1400
    specific-location: true
    cost: 50
    launching-radius: 8
    landing-radius: 6
    ocean-checker: true
