messages:
  no_space: "&cThere are blocks above you"
  land_near_town: "&cThe landing location is near a town"
  launch_near_town: "&cThe launching location is near a town"
  outside_range: "&cThe specified location is outside the range"
  not_safe: "&cThe landing location is not safe"
  no-permission: "&cYou don't have permission to use this"
  send-usage: "&cUsage: /rocket send <player-name> <rocket-id>"
  invalid-target: "&cPlease enter a valid target"
  invalid-rocket: "&cPlease enter a valid rocket id"
  no-specific-location: "&cYou cannot use specific location for this rocket"
  no-console: "&cThis command can only be executed by a player"
  travel-usage: "&cUsage: /rocket travel <rocket-id>"
  already-traveling: "&cYou are already traveling"
  confirmation: "&cThe cost for this travel is %cost%. Are you sure you want to travel?"
  confirmation-accept: "&c[ACCEPT]"
  confirmation-deny: "&c[DENY]"

settings:
  apply-texturepack: false
  url: "https://www.dropbox.com/sh/4dflqzxa3ukcxgg/AAAVWn-u1ufOoY0l8bD3CqqQa?dl=1"
  item:
    #item the player gets with the rocket give command, used to deploy rocket
    inventory:
      material: RABBIT_HIDE
      custom-model-data: 11
      name: "&cRocket"
      description:
        - "right click the ground holding this to deploy the rocket"
        - "once deployed, sit inside, run a destination command, and insert fuel while inside rocket"
    liftoff:
      material: RABBIT_HIDE
      custom-model-data: 11
    landing:
      material: RABBIT_HIDE
      custom-model-data: 12
      #negative values spawn particles below the model, positive particles spawn above the model, negative particles shoot downwards, positive they shoot upwards
      landing-particle-offset: -3.0
      #if possible a method to select particles to use, sizes, how many, etc?
  launch:
    time: 5 # in seconds
    speed: 2
  land:
    distance: 50
  towny-integration:
    use-towny: true
    launch:
      own-town: true
      own-nation: true
      ally-territory: true
      enemy-territory: false
      #distance in chunks from a non allowed launching zone (enemy territory for example)
      #set to 0 to prevent launching directly on top of enemy towns but still being able to launch right next to their chunks
      distance-from-unathorized-zones: 8
    land:
      own-town: true
      own-nation: true
      ally-territory: true
      enemy-territory: false
      #distance in chunks from a non allowed landing zone (enemy territory for example)
      #set to 0 to prevent landing directly on top of enemy towns but still being able to land right next to their chunks
      #this only affects the initial launch coordinates entered, if rockets are allowed to move during landing and they move into not allowed chunks they can still land there
      distance-from-unathorized-zones: 8

rockets:
  MARS:
    launching-message: "&aYou are launching to Mars"
    landing-message: "&bYou have been landed to Mars"
    world: world
    location: 100,1300
    location2: 300,-1400
    specific-location: true
    cost: 100
    ocean-checker: true
  JUPITER:
    launching-message: "&aYou are launching to Jupiter"
    landing-message: "&bYou have been landed to Jupiter"
    world: world_nether
    location: 100,1300
    location2: 300,-1400
    specific-location: true
    cost: 50
    ocean-checker: true
