debug: false
messages:
  no_space: "&cThere are blocks above you"
  land_near_town: "&cThe landing location is near a town"
  launch_near_town: "&cThe launching location is near a town"
  land_not_allowed: "&cYou cannot land inside %territory_type%"
  launch_not_allowed: "&cYou cannot launch from %territory_type%"
  outside_range: "&cThe specified location is outside the range"
  not_safe: "&cThe landing location is not safe"
  no-permission: "&cYou don't have permission to use this"
  send-usage: "&cUsage: /rocket send <player-name> <rocket-id>"
  invalid-target: "&cPlease enter a valid target"
  invalid-rocket: "&cPlease enter a valid rocket id"
  no-specific-location: "&cYou cannot use specific location for this rocket"
  no-console: "&cThis command can only be executed by a player"
  travel-usage: "&cUsage: /rocket travel <rocket-id>"
  already-traveling: "&cYou are already traveling"
  not-inside-rocket: "&cYou have to be inside a rocket to travel!"
  rocket-place-not-top: "&cYou have to place the rocket on top of the block"
  confirmation: "&cThe cost for this travel is %cost%. Are you sure you want to travel?"
  pickup-rocket: "&aPicking up the rocket, please stay still for 5 seconds"
  pickup-rocket-fail: "§c§lRocket placement cancelled!"
  already-picking-up: "&cRocket is already being picked up by another player"
  pickup-rocket-success: "&aRocket picked up!"
  place-rocket: "&aPlacing down the rocket, please stay still for 5 seconds"
  place-rocket-fail: "§c§lRocket placement cancelled!"
  fueling-rocket: "&cadding fuel to rocket, please wait"
  added-fuel: "&aFuel added! Remaining fuel needed: %fuel%"
  invalid-fuel: "that is not a valid fuel item"
  fueling-complete: "fuel added! lifting off in 10 seconds..."
  already-fueling: "&cRocket is currently being fueled, please wait for it to finish for adding more fuel!"
  launch-off-timer-message: "&cLiftoff in %time% seconds"

settings:
  apply-texturepack: false
  url: "https://www.dropbox.com/sh/4dflqzxa3ukcxgg/AAAVWn-u1ufOoY0l8bD3CqqQa?dl=1"
  item:
    #item the player gets with the rocket give command, used to deploy rocket
    inventory:
      material: RABBIT_HIDE
      custom-model-data: 11
      name: "&cRocket"
      description:
        - "right click the ground holding this to deploy the rocket"
        - "once deployed, sit inside, run a destination command, and insert fuel while inside rocket"
    liftoff:
      material: RABBIT_HIDE
      custom-model-data: 11
    landing:
      material: RABBIT_HIDE
      custom-model-data: 12
      #negative values spawn particles below the model, positive particles spawn above the model, negative particles shoot downwards, positive they shoot upwards
      landing-particle-offset: -3.0
      #if possible a method to select particles to use, sizes, how many, etc?
  launch:
    #how long should the rocket wait after being fueled before actually lifting off
    liftoff-time: 10
    #how long the rocket rides into the air before teleporting to another dimension/location and doing landing animation
    time: 5 # in seconds
    #how fast the rocket moves in the air
    speed: 2
    #how long in seconds can a rocket be on the ground with no one inside before it breaks back into its item form
    inactivity-timer: 10
    #should players be invincible in the rocket while preparing for launch?
    launch-invincibility: false
    require-fuel: true
    fuel:
      dried_kelp_block: 10
      coal_block: 90
    #if set to true, each fuel item must be inserted one by one, can be tedious, if false inserting fuel will insert as much fuel item in the hand that is needed for the trip, or assuming there isnt enough fuel, the whole stack
    insert-fuel-individually: true
  land:
    #distance from the ground the rocket spawns in at, rocket falls from this distance until it lands on the ground
    distance: 50
    land-freefall-time: 2
    thruster-fall-speed: -0.3
    #allows players to slightly adjust the rocket's position during landing using wasd, similar to the hellpods in helldivers 2 or drop pods in planetside 2
    allow-movement: false
    movement-speed: 0.15
    #drops the rocket item on landing, in case you want rockets to be reusable
    drop-rocket-on-landing: true
    #time in seconds that a player remains in the rocket once landed before being dismounted, prevents players from landing right on top of enemies and immediately being able to attack them
    # set to 0 to disable
    landing-dismount-time: 5
    #should the player be invulnerable to damage while still in the rocket and waiting to be dismounted?
    protect-while-dismounting: false
  deployment:
    #how long it takes after right clicking with the item to deploy the rocket
    place-time: 5
    #how long it takes after left clicking rocket from outside before it turns into its item form
    pickup-time: 5
    #how long it takes to insert fuel
    fuel-time: 2
  towny-integration:
    use-towny: true
    launch:
      own-town: true
      own-nation: true
      ally-territory: true
      enemy-territory: false
      neutral-territory: true
      #distance in chunks from a non allowed launching zone (enemy territory for example)
      #set to 0 to prevent launching directly on top of enemy towns but still being able to launch right next to their chunks
      distance-from-unathorized-zones: 8
    land:
      own-town: true
      own-nation: true
      ally-territory: true
      enemy-territory: false
      neutral-territory: true
      #distance in chunks from a non allowed landing zone (enemy territory for example)
      #set to 0 to prevent landing directly on top of enemy towns but still being able to land right next to their chunks
      #this only affects the initial launch coordinates entered, if rockets are allowed to move during landing and they move into not allowed chunks they can still land there
      distance-from-unathorized-zones: 8

rockets:
  MARS:
    launching-message: "&aYou are launching to Mars"
    landing-message: "&bYou have been landed to Mars, please wait 5 seconds till dismount"
    world: world
    location: 100,1300
    location2: 300,-1400
    specific-location: true
    cost: 100
    ocean-checker: true
  JUPITER:
    launching-message: "&aYou are launching to Jupiter"
    landing-message: "&bYou have been landed to Jupiter, please wait 5 seconds till dismount"
    world: world_nether
    location: 100,1300
    location2: 300,-1400
    specific-location: true
    cost: 50
    ocean-checker: true
