name: MortisRockets
version: '${project.version}'
main: com.mortisdevelopment.mortisrockets.MortisRockets
api-version: '1.18'
softdepend:
  - EssentialsX
  - Towny
depend:
  - ProtocolLib
commands:
  rocket:
    aliases: [rockets, mortisrocket, mortisrockets]
  giverocket:
    description: Give a player a rocket