config:
  url: "https://www.dropbox.com/sh/4dflqzxa3ukcxgg/AAAVWn-u1ufOoY0l8bD3CqqQa?dl=1"
  item:
    material: RABBIT_HIDE
    custom-model-data: 11
  rocket:
    launch:
      time: 5 #in seconds
      speed: 2
    land:
      distance: 50
    messages:
      no_space: "&cThere are blocks above you"
      land_near_town: "&cThe landing location is near a town"
      launch_near_town: "&cThe launching location is near a town"
      outside_range: "&cThe specified location is outside the range"
      not_safe: "&cThe landing location is not safe"
      could_not_find: "&cCould not find a suitable location"
  MARS:
    launching-message: "&aYou are launching to Mars"
    landing-message: "&bYou have been landed to Mars"
    world: world
    location: 100,1300
    location2: 300,-1400
    specific-location: true
    cost: 100
    launching-radius: 8
    landing-radius: 6
    ocean-checker: true
  JUPITER:
    launching-message: "&aYou are launching to Mars"
    landing-message: "&bYou have been landed to Jupiter"
    world: world_nether
    location: 100,1300
    location2: 300,-1400
    specific-location: true
    cost: 50
    launching-radius: 8
    landing-radius: 6
    ocean-checker: true
